"""
Django settings for vinateria_3_hermanos project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os
from decouple import config
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Load local .env if present (ignored by git) to improve local developer experience.
load_dotenv(dotenv_path=BASE_DIR / '.env')

# Exceptions and helpers
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# SECURITY: do not fall back to an insecure SECRET_KEY in production.
# Require deployment to set SECRET_KEY in environment variables or secrets manager.
SECRET_KEY = config('SECRET_KEY')
if not SECRET_KEY:
    # Allow local development by setting DJANGO_DEVELOPMENT=1 in env, otherwise fail fast
    if os.getenv('DJANGO_DEVELOPMENT', '0') == '1':
        # Generate an ephemeral secret key for local development (not stored in repo)
        SECRET_KEY = os.getenv('SECRET_KEY') or get_random_secret_key()
    else:
        raise ImproperlyConfigured('The SECRET_KEY environment variable is not set.')

# Default to True for local development unless explicitly overridden.
DEBUG = config('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

# Clave de API de Google Maps
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', '')

# ALLOWED_HOSTS should be provided via environment variable (comma-separated)
# e.g. ALLOWED_HOSTS=example.com,myapp.onrender.com
raw_hosts = config('ALLOWED_HOSTS', '')
if raw_hosts:
    ALLOWED_HOSTS = [
    'vinateria-3-hermanos-ucsx.onrender.com', 
    '.onrender.com',
    'localhost', 
    '127.0.0.1',
    '*'
]
else:
   ALLOWED_HOSTS = [
    'vinateria-3-hermanos-ucsx.onrender.com', 
    '.onrender.com',
    'localhost', 
    '127.0.0.1',
    '*'  # El comodín asegura que la petición pase sí o sí
]

# ESTA LÍNEA ES LA CLAVE: Añádela justo debajo del bloque anterior
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 'django_ratelimit',
    'tienda',

    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Google reCAPTCHA v2
    'django_recaptcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tienda.middleware.NoCacheAuthenticatedMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'vinateria_3_hermanos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                
                'django.template.context_processors.debug', 
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tienda.context_processors.google_maps_config',
            ],
            
        },
    },
]

WSGI_APPLICATION = 'vinateria_3_hermanos.wsgi.application'

import dj_database_url

# Database
# Usa DATABASE_URL (Render/Supabase) con fallback a variables individuales
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=None) or
        f"postgresql://{config('DB_USER')}:{config('DB_PASSWORD')}@{config('DB_HOST')}:{config('DB_PORT', '5432')}/{config('DB_NAME')}",
        conn_max_age=600,
        ssl_require=True,
    )
}

# Keep DB connections alive for reuse (useful with Supabase pooler)
CONN_MAX_AGE = int(config('CONN_MAX_AGE', '600'))

# Cache configuration for django-ratelimit
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-mx'  # Español de México

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Media files (imágenes subidas por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET')
PAYPAL_MODE = config('PAYPAL_MODE', 'sandbox')

# Configuración de Email (SMTP Gmail via .env)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_TIMEOUT = 10  # segundos — evita que la conexión SMTP se cuelgue
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Vinatería 3 Hermanos <noreply@vinateria3hermanos.com>')

# ── Google reCAPTCHA v2 ──────────────────────────────────────────────────────────────────────
RECAPTCHA_PUBLIC_KEY  = config('RECAPTCHA_PUBLIC_KEY',  default='6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')
RECAPTCHA_PRIVATE_KEY = config('RECAPTCHA_PRIVATE_KEY', default='6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']
# ──────────────────────────────────────────────────────────────────────────────

# ── Django Allauth — Correos ─────────────────────────────────────────────────────────────
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'
ACCOUNT_EMAIL_VERIFICATION = 'none'
PASSWORD_RESET_TIMEOUT = 604800  # 7 días
# ──────────────────────────────────────────────────────────────────────────────