"""
Django settings for vinateria_3_hermanos project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
# Only load .env for local development (avoid accidentally using repo .env in production)
if os.getenv('DJANGO_DEVELOPMENT', '0') == '1':
    load_dotenv(dotenv_path=BASE_DIR / '.env')

# Exceptions and helpers
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# SECURITY: do not fall back to an insecure SECRET_KEY in production.
# Require deployment to set SECRET_KEY in environment variables or secrets manager.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    # Allow local development by setting DJANGO_DEVELOPMENT=1 in env, otherwise fail fast
    if os.getenv('DJANGO_DEVELOPMENT', '0') == '1':
        # Generate an ephemeral secret key for local development (not stored in repo)
        SECRET_KEY = os.getenv('SECRET_KEY') or get_random_secret_key()
    else:
        raise ImproperlyConfigured('The SECRET_KEY environment variable is not set.')

# Default to False for safety. Set DEBUG=1 only in trusted dev environments.
DEBUG = True

# ALLOWED_HOSTS should be provided via environment variable (comma-separated)
# e.g. ALLOWED_HOSTS=example.com,myapp.onrender.com
raw_hosts = os.getenv('ALLOWED_HOSTS', '')
if raw_hosts:
    ALLOWED_HOSTS = [
    'vinateria-3-hermanos-ucsx.onrender.com', 
    '.onrender.com',
    'localhost', 
    '127.0.0.1',
    '*'
]
else:
   ALLOWED_HOSTS = [
    'vinateria-3-hermanos-ucsx.onrender.com', 
    '.onrender.com',
    'localhost', 
    '127.0.0.1',
    '*'  # El comodín asegura que la petición pase sí o sí
]

# ESTA LÍNEA ES LA CLAVE: Añádela justo debajo del bloque anterior
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_ratelimit',
    'tienda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'tienda.middleware.NoCacheAuthenticatedMiddleware',
]

ROOT_URLCONF = 'vinateria_3_hermanos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                
                'django.template.context_processors.debug', 
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tienda.context_processors.google_maps_config',
            ],
            
        },
    },
]

WSGI_APPLICATION = 'vinateria_3_hermanos.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Keep DB connections alive for reuse (useful with Supabase pooler)
CONN_MAX_AGE = int(os.getenv('CONN_MAX_AGE', '600'))

# Cache configuration for django-ratelimit
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-mx'  # Español de México

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Media files (imágenes subidas por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# --- Configuración de django-allauth (Actualizada) ---
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True

# --- Configuración de autenticación y redirecciones ---
LOGIN_URL = 'tienda:login'
LOGIN_REDIRECT_URL = 'tienda:index'
LOGOUT_REDIRECT_URL = 'tienda:index'

# --- Configuración de pasarela de pagos ---
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_SECRET = os.getenv('PAYPAL_SECRET', '')
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')

# --- Configuración de Google Maps ---
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY', '')

# --- Configuración de django-ratelimit ---
RATELIMIT_USE_CACHE = 'default'
SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']

# --- Configuración de Sesión ---
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True' if not DEBUG else False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')

# Security headers for production
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True' if not DEBUG else False
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True' if not DEBUG else False
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000')) if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True' if not DEBUG else False
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True') == 'True' if not DEBUG else False

# Clickjacking protection
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

# CSRF trusted origins: comma separated
raw_csrf = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if raw_csrf:
    CSRF_TRUSTED_ORIGINS = [u.strip() for u in raw_csrf.split(',') if u.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

# Production-ready secure defaults (suitable for Render). These can be
# overridden explicitly by setting DJANGO_DEVELOPMENT=1 for local development.
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
# Set an explicit HSTS default (one year). This is a literal so static checks
# detect it; deployments can override via env var if needed.
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Development override: if DJANGO_DEVELOPMENT=1, relax some flags for local dev
if os.getenv('DJANGO_DEVELOPMENT', '0') == '1':
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Default clickjacking protection
X_FRAME_OPTIONS = 'DENY'

# If CSRF_TRUSTED_ORIGINS not provided, build from ALLOWED_HOSTS (https)
if not CSRF_TRUSTED_ORIGINS and ALLOWED_HOSTS:
    CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h]
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False    