[pytest]
DJANGO_SETTINGS_MODULE = vinateria_3_hermanos.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = -q --strict-markers
norecursedirs = .git .venv .pytest_cache vinateria-3-hermanos-test
testpaths = tienda vinateria_3_hermanos
