# Generated by Django 6.0.2 on 2026-03-27 21:58

# Generated by Django 5.0.6 on 2026-03-27 21:30

from django.db import migrations
from django.utils.text import slugify

def create_initial_products(apps, schema_editor):
    """
    Crea categorías y productos iniciales para la tienda.
    """
    Categoria = apps.get_model('tienda', 'Categoria')
    Producto = apps.get_model('tienda', 'Producto')

    # --- Crear Categorías ---
    categorias_data = [
        "Tequila", "Whisky", "Ron", "Vino Tinto", "Vino Blanco", "Mezcal", "Ginebra"
    ]
    categorias = {}
    for nombre_cat in categorias_data:
        slug = slugify(nombre_cat)
        categoria, created = Categoria.objects.get_or_create(
            nombre=nombre_cat,
            defaults={'slug': slug}
        )
        categorias[nombre_cat] = categoria

    # --- Crear Productos ---
    productos_data = [
        # Tequilas
        {'nombre': 'Don Julio 70', 'cat': 'Tequila', 'precio': 850.00, 'stock': 50, 'desc': 'Tequila cristalino añejo, suave y complejo.'},
        {'nombre': 'Maestro Dobel Diamante', 'cat': 'Tequila', 'precio': 750.00, 'stock': 60, 'desc': 'Reposado, añejo y extra-añejo, filtrado para un sabor suave.'},
        {'nombre': 'José Cuervo Tradicional', 'cat': 'Tequila', 'precio': 450.00, 'stock': 100, 'desc': 'Tequila reposado 100% de agave, ideal para margaritas.'},
        {'nombre': '1800 Cristalino', 'cat': 'Tequila', 'precio': 900.00, 'stock': 40, 'desc': 'Añejo cristalino con notas de madera y vainilla.'},

        # Whiskies
        {'nombre': 'Johnnie Walker Black Label', 'cat': 'Whisky', 'precio': 950.00, 'stock': 70, 'desc': 'Whisky escocés mezclado de 12 años, ahumado y frutal.'},
        {'nombre': 'Jack Daniel\'s Old No. 7', 'cat': 'Whisky', 'precio': 650.00, 'stock': 80, 'desc': 'Whisky de Tennessee, filtrado en carbón de arce para mayor suavidad.'},
        {'nombre': 'Macallan 12 Sherry Oak', 'cat': 'Whisky', 'precio': 2500.00, 'stock': 20, 'desc': 'Single malt con ricas notas de frutos secos y especias.'},
        {'nombre': 'Jameson Irish Whiskey', 'cat': 'Whisky', 'precio': 550.00, 'stock': 90, 'desc': 'Whisky irlandés de triple destilación, excepcionalmente suave.'},

        # Rones
        {'nombre': 'Zacapa 23', 'cat': 'Ron', 'precio': 1300.00, 'stock': 30, 'desc': 'Ron de Guatemala envejecido en sistema solera, dulce y complejo.'},
        {'nombre': 'Havana Club 7 Años', 'cat': 'Ron', 'precio': 600.00, 'stock': 75, 'desc': 'Ron cubano oscuro con notas de tabaco, cacao y frutas tropicales.'},
        {'nombre': 'Bacardi Carta Blanca', 'cat': 'Ron', 'precio': 300.00, 'stock': 120, 'desc': 'Ron blanco ligero, perfecto para coctelería como el Mojito.'},

        # Vinos Tintos
        {'nombre': 'Casa Madero 3V', 'cat': 'Vino Tinto', 'precio': 550.00, 'stock': 60, 'desc': 'Vino mexicano de Parras, Coahuila. Mezcla de Cabernet, Merlot y Tempranillo.'},
        {'nombre': 'Concha y Toro Casillero del Diablo', 'cat': 'Vino Tinto', 'precio': 350.00, 'stock': 100, 'desc': 'Cabernet Sauvignon chileno, con notas de cereza y cassis.'},
        {'nombre': 'Robert Mondavi Private Selection', 'cat': 'Vino Tinto', 'precio': 700.00, 'stock': 50, 'desc': 'Cabernet Sauvignon de California, envejecido en barricas de roble.'},

        # Vinos Blancos
        {'nombre': 'Monte Xanic Sauvignon Blanc', 'cat': 'Vino Blanco', 'precio': 480.00, 'stock': 65, 'desc': 'Vino mexicano del Valle de Guadalupe, cítrico y refrescante.'},
        {'nombre': 'Santa Margherita Pinot Grigio', 'cat': 'Vino Blanco', 'precio': 650.00, 'stock': 55, 'desc': 'Vino italiano fresco y seco con aromas de manzana dorada.'},

        # Mezcales
        {'nombre': '400 Conejos Joven', 'cat': 'Mezcal', 'precio': 700.00, 'stock': 45, 'desc': 'Mezcal artesanal de Oaxaca, con un balance perfecto entre ahumado y cítrico.'},
        {'nombre': 'Montelobos Espadín', 'cat': 'Mezcal', 'precio': 850.00, 'stock': 40, 'desc': 'Mezcal orgánico con notas herbales y de agave cocido.'},

        # Ginebras
        {'nombre': 'Hendrick\'s Gin', 'cat': 'Ginebra', 'precio': 980.00, 'stock': 50, 'desc': 'Ginebra infusionada con pepino y pétalos de rosa.'},
        {'nombre': 'Tanqueray London Dry Gin', 'cat': 'Ginebra', 'precio': 600.00, 'stock': 80, 'desc': 'Ginebra clásica con un fuerte sabor a enebro, ideal para Gin & Tonic.'},
    ]

    for data in productos_data:
        Producto.objects.get_or_create(
            nombre=data['nombre'],
            defaults={
                'categoria': categorias[data['cat']],
                'descripcion': data['desc'],
                'precio': data['precio'],
                'stock': data['stock'],
                'slug': slugify(data['nombre'])
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_products),
    ]
