# Generated by Django 6.0.2 on 2026-05-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_populate_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
