# Generated by Django 6.0.2 on 2026-05-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_perfilcliente_email_verificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcliente',
            name='email_verificado',
        ),
    ]
